version: '3.4'

services:
  hubspotoauth:
    image: hubspotoauth
    build:
      context: lesson-3-foundations-of-authenticating-integrations/02-the-basics-of-the-oauth-flow
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
